spring:
  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: "devices"
  influxdb:
    url: http://localhost:8086
    username: user
    database: test
    retention-policy: autogen
  mqtt:
    uris:
      - "tcp://localhost:1883"
  stomp:
    uri: "http://localhost:8080/channels"